name: "EKS Infrastructure Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-south-1"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials via OIDC"
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsEKSRole
          aws-region: ap-south-1

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3.1.2

      - name: "Generate SSH Key Files from Secrets"
        run: |
          mkdir -p files
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./files/eks-key.pub

      - name: "Terraform Init & Apply"
        run: |
          terraform init
          terraform apply -auto-approve

