name: "EKS Infrastructure Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-south-1"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This ensures Gitleaks scans your history, not just the last line

      - name: "Run GitLeaks scan"
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug ref
        run: echo "REF=${{ github.ref }}"

      - name: Show OIDC token claims
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(Buffer.from(id_token.split('.')[1], 'base64').toString());
            console.log(payload);

      - name: "Configure AWS Credentials via OIDC"
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::381492299804:role/GitHubActionsWorkflowRole
          aws-region: ap-south-1

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3.1.2

      - name: "Generate SSH Key Files from Secrets"
        run: |
          mkdir -p files
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./files/eks-key.pub

      - name: "Terraform Init & Apply"
        run: |
          terraform init
          terraform apply -auto-approve

